services:
  hydra:
    image: oryd/hydra:v2.1.2
    ports:
      - "4444:4444"
      - "4445:4445" 
      - "5555:5555" 
    command: serve all --dev
    environment:
      - SECRETS_SYSTEM=global_secret_to_encrypt_db
      - DSN=postgres://${POSTGRES_DB_USERNAME}:${POSTGRES_DB_PWD}@postgresd:5432/${POSTGRES_DB_NAME}?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - hydranet

  hydra-migrate:
    image: oryd/hydra:v2.1.2
    environment:
      - DSN=postgres://${POSTGRES_DB_USERNAME}:${POSTGRES_DB_PWD}@postgresd:5432/${POSTGRES_DB_NAME}?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - hydranet

  postgresd:
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PWD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    networks:
      - hydranet

networks:
  hydranet:

